TestCoreApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestCoreApp.Models;
using TestCoreApp.Repository.Base;

namespace TestCoreApp.Controllers
{
	[Authorize(Roles = clsRoles.roleAdmin)]
    public class CategoryController : Controller
    {
        public CategoryController(IUnitOfWork _myUnit) 
        {
            //_repository = repository;
			myUnit = _myUnit;
        }
        //private IRepository<Category> _repository;
        
        private readonly IUnitOfWork myUnit;

		//public IActionResult Index()
		//{
		//    return View(_repository.FindAll());
		//}
		public async Task<IActionResult> Index()
		{
			var oneCat = myUnit.categories.SelectOne(x => x.Name == "Mobiles");
			var allCat = await myUnit.categories.FindAllAsync("Items");
			return View(allCat);
		}

		//GET
		public IActionResult New()
		{
			return View();
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult New(Category category)
		{
			if (ModelState.IsValid)
			{
                if (category.clientFile != null)
                {
					MemoryStream stream = new MemoryStream();
					category.clientFile.CopyTo(stream);
					category.dbImage = stream.ToArray();					
                }

                myUnit.categories.AddOne(category);
				return RedirectToAction("Index");
			}
			else
			{
				return View(category);
			}
		}

		//GET
		public IActionResult Edit(int? Id)
		{
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var category = myUnit.categories.FindById(Id.Value);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Category category)
		{
			if (ModelState.IsValid)
			{
                myUnit.categories.UpdateOne(category);
				return RedirectToAction("Index");
			}
			else
			{
				return View(category);
			}
		}

		//GET
		public IActionResult Delete(int? Id)
		{
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var category = myUnit.categories.FindById(Id.Value);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(Category category)
		{
            myUnit.categories.DeleteOne(category);
			TempData["successData"] = "Category has been deleted successfully";
			return RedirectToAction("Index");
		}

	}
}

TestCoreApp/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestCoreApp.Data;
using TestCoreApp.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace TestCoreApp.Controllers
{
    [Authorize(Roles = clsRoles.roleAdmin)]
    public class ItemsController : Controller
    {
        public ItemsController(AppDbContext db, IHostingEnvironment host)
        {
            _db = db;
            _host = host;
        }

        private readonly IHostingEnvironment _host;

        private readonly AppDbContext _db;
        public IActionResult Index()
        {
            IEnumerable<Item> itemList = _db.Items.Include(c => c.Category).ToList();
            return View(itemList);
        }

        //GET
        public IActionResult New()
        {
            CreateSelectList();
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(Item item)
        {
            if (item.Name == "100")
            {
                ModelState.AddModelError("Name", "Name Can't equal 100");
            }

            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if(item.clientFile != null)
                {
                    string myUpload = Path.Combine(_host.WebRootPath, "images");
                    fileName = item.clientFile.FileName;
                    string fullPath = Path.Combine(myUpload, fileName);
                    item.clientFile.CopyTo(new FileStream(fullPath, FileMode.Create));
                    item.imagePath = fileName;
                }
                _db.Items.Add(item);
                _db.SaveChanges();
                TempData["successData"] = "Item has been added successfully";
                return RedirectToAction("Index");
            }
            else {
                return View(item);
            }

        }

        public void CreateSelectList(int selectId = 1)
        {
            //List<Category> categories = new List<Category>{
            //new Category() { Id = 0, Name = "Select Category" },
            //new Category() { Id = 1, Name = "Computers" },
            //new Category() { Id = 2, Name = "Mobiles" },
            //new Category() { Id = 3, Name = "Electric machines" },
            //};
            List<Category> categories = _db.Categories.ToList();
            SelectList listItems = new SelectList(categories, "Id", "Name", selectId);
            ViewBag.CategoryList = listItems;
        }

        //GET
        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0) {
                return NotFound();
            }
            var item = _db.Items.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            CreateSelectList(item.CategoryId);
            return View(item);
        }

        //TODO Add editing for images. same as New()

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Item item)
        {
            if (item.Name == "100")
            {
                ModelState.AddModelError("Name", "Name Can't equal 100");
            }

            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if (item.clientFile != null)
                {
                    string myUpload = Path.Combine(_host.WebRootPath, "images");
                    fileName = item.clientFile.FileName;
                    string fullPath = Path.Combine(myUpload, fileName);
                    item.clientFile.CopyTo(new FileStream(fullPath, FileMode.Create));
                    item.imagePath = fileName;
                }
                _db.Items.Update(item);
                _db.SaveChanges();
                TempData["successData"] = "Item has been added successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return View(item);
            }

        }

        //GET
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var item = _db.Items.Find(Id);
            if (item == null)
            {
                return NotFound();
            }
            CreateSelectList(item.CategoryId);
            return View(item);
        }

        //POST
        [HttpPost, ActionName("Delete")]        //asp-action for form in Delete.cshtml is name here.
        [ValidateAntiForgeryToken]
        public IActionResult DeleteItem(int? Id)
        {
            var item = _db.Items.Find(Id);
            if(item == null)
            {
                return NotFound();
            }

			_db.Remove(item);
			_db.SaveChanges();
            TempData["successData"] = "Item has been deleted successfully";
            return RedirectToAction("Index");
		}
    }
}

TestCoreApp/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using Newtonsoft.Json;
using System.Collections.Generic;
using TestCoreApp.Models;

namespace TestCoreApp.Controllers
{
	[Authorize(Roles = clsRoles.roleAdmin)]
	public class RolesController : Controller
	{
		public RolesController(UserManager<IdentityUser> user, RoleManager<IdentityRole> roles)
		{
			_user = user;
			_roles = roles;
		}

		private readonly UserManager<IdentityUser> _user;
		private readonly RoleManager<IdentityRole> _roles;

		public async Task<IActionResult> Index()
		{
			var _users = await _user.Users.ToListAsync();
			return View(_users);
		}

		public async Task<IActionResult> addRoles(string userId)
		{
			var user = await _user.FindByIdAsync(userId);
			var userRoles = await _user.GetRolesAsync(user);

			var allRoles = await _roles.Roles.ToListAsync();
			if (allRoles != null)
			{
				var roleList = allRoles.Select(r => new roleViewModel()
				{
					roleId = r.Id,
					roleName = r.Name,
					useRole = userRoles.Any(x => x == r.Name)
				});
				ViewBag.userName = user.UserName;
				ViewBag.userId = userId;
				return View(roleList);
			}
			else
				return NotFound();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> addRoles(string userId, string jsonRoles)
		{
			var user = await _user.FindByIdAsync(userId);

			List<roleViewModel> myRoles =
				JsonConvert.DeserializeObject<List<roleViewModel>>(jsonRoles);

			if (user != null)
			{
				var userRoles = await _user.GetRolesAsync(user);

				foreach (var role in myRoles)
				{
					if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
					{
						await _user.RemoveFromRoleAsync(user, role.roleName.Trim());
					}

					if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
					{
						await _user.AddToRoleAsync(user, role.roleName.Trim());
					}
				}

				return RedirectToAction(nameof(Index));
			}
			else
				return NotFound();
		}
	}
}

TestCoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TestCoreApp</title>
	<link rel="stylesheet" href="~/css/bootswatchStyle.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 
	<link rel="stylesheet" href="~/TestCoreApp.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestCoreApp</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" hidden asp-area="Employees" asp-controller="Home" asp-action="Index">Employees</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Employees" asp-controller="Employees" asp-action="Index">Employees List</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">User Roles</a>
						</li>
					</ul>

					<partial name="_LoginPartial" class="text-white">

					</partial>

				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - TestCoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TestCoreApp/Views/Shared/_Notifications.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["successData"] != null)
{
	<h3 style="color:lightgreen">
		@TempData["successData"]
	</h3>

	<script type="text/javascript">
		toastr.success('@TempData["successData"]', 'Success')
	</script>
} 

@if (TempData["errorData"] != null)
{
	<h3 style="color:lightgreen">
		@TempData["errorData"]
	</h3>

	<script type="text/javascript">
		toastr.error('@TempData["errorData"]', 'Error')
	</script>
} 